import Mathlib

/-!
This snippet is about:

  extendStep
  extendStep_fst
  extendStepRand
  extendStepRand_fst

found at line 322 of 327, near the end of this file.

Everything above it is the companion's own dependencies, inlined so that
this file needs nothing but mathlib. -/

/-! Inlined dependency: LeanTest/HardProblems/Core.lean -/


/-!
# Core partially observed system

The companion modules share one small stochastic interface: a state transition
kernel controlled by an action and an observation kernel on the resulting state
space. More specialized task, policy, horizon, cost, and resource parameters
are introduced in the modules that use them.
-/

namespace HardProblems

/-- A countably supported partially observed stochastic system. The transition
kernel is action-indexed; the observation kernel emits a law from each latent
state. Admissible policy classes and resource bounds are separate parameters. -/
structure POSystem (S A O : Type*) where
  T : S → A → PMF S
  Z : S → PMF O

end HardProblems


/-! Target module: LeanTest/HardProblems/Dynamics.lean -/


/-!
# Controlled dynamics, lag, probes, and state augmentation

These results share the same machinery: trajectory distributions of a
controlled Markov step.

Results proved:

* `constrainedReachable_mono_alpha`, `constrainedReachable_mono_goal`:
  chance-constrained reachability behaves monotonically in the risk budget
  and the target set.
* `AuthorityMap.classify`: the direct/induced/exogenous partition classifies
  every transformation label exactly once.
* `no_signal_before_lag`: before the observability lag, the declared
  discrepancy remains below `δ`.
* `extendStep_fst`: under the supplied augmentation architecture, the
  `S`-marginal of one product-state step is the current `P`-dependent kernel.
* `goodhart_witness_example`: a two-line concrete instance of metric-goal
  decoupling under intervention.
* `not_decisionRelevant_iff`: a probe is decision-irrelevant exactly when its
  selected action is constant across possible outcomes.
-/

namespace HardProblems

noncomputable section

open scoped ENNReal
open MeasureTheory

variable {S A O P : Type*}

/-! ## Trajectories -/

/-- Fold a Markov policy and a transition kernel into a closed-loop step. -/
def stepOf (T : S → A → PMF S) (π : S → PMF A) : S → PMF S :=
  fun s => (π s).bind (T s)

/-- Distribution over length-`(n+1)` trajectories (as lists, initial state
first) generated by a step kernel. -/
def rollout (step : S → PMF S) : ℕ → S → PMF (List S)
  | 0, s => PMF.pure [s]
  | n + 1, s => (step s).bind fun s' => (rollout step n s').map (s :: ·)

/-- The trajectory's final listed state lies in `Gset`, and every listed state,
including the initial state, lies in `C`. -/
def SafeGoal (Gset C : Set S) : Set (List S) :=
  {l | (∃ g ∈ Gset, l.getLast? = some g) ∧ ∀ z ∈ l, z ∈ C}

/-- Success probability of a policy for the safe-reachability event. -/
def successProb (T : S → A → PMF S) (π : S → PMF A)
    (Gset C : Set S) (n : ℕ) (s₀ : S) : ℝ≥0∞ :=
  (rollout (stepOf T π) n s₀).toOuterMeasure (SafeGoal Gset C)

/-- Exact-horizon safe reachability for full-state Markov policies: some policy
has a safe trajectory ending in `Gset` at time `n` with mass at least the
truncated threshold `1 - α`. For `α ≤ 1` this has the usual risk-budget reading.
This is not an observation-history policy definition. -/
def ConstrainedReachable (T : S → A → PMF S) (Pols : Set (S → PMF A))
    (Gset C : Set S) (α : ℝ≥0∞) (n : ℕ) (s₀ : S) : Prop :=
  ∃ π ∈ Pols, 1 - α ≤ successProb T π Gset C n s₀

/-- A larger risk budget can only help. -/
theorem constrainedReachable_mono_alpha
    {T : S → A → PMF S} {Pols : Set (S → PMF A)} {Gset C : Set S}
    {α α' : ℝ≥0∞} {n : ℕ} {s₀ : S} (hα : α ≤ α')
    (h : ConstrainedReachable T Pols Gset C α n s₀) :
    ConstrainedReachable T Pols Gset C α' n s₀ := by
  obtain ⟨π, hπ, hp⟩ := h
  exact ⟨π, hπ, le_trans (tsub_le_tsub_left hα 1) hp⟩

/-- Enlarging the target set can only help. -/
theorem constrainedReachable_mono_goal
    {T : S → A → PMF S} {Pols : Set (S → PMF A)} {Gset Gset' C : Set S}
    {α : ℝ≥0∞} {n : ℕ} {s₀ : S} (hG : Gset ⊆ Gset')
    (h : ConstrainedReachable T Pols Gset C α n s₀) :
    ConstrainedReachable T Pols Gset' C α n s₀ := by
  obtain ⟨π, hπ, hp⟩ := h
  refine ⟨π, hπ, le_trans hp (measure_mono ?_)⟩
  rintro l ⟨⟨g, hg, hlast⟩, hsafe⟩
  exact ⟨⟨g, hG hg, hlast⟩, hsafe⟩

/-- Recovery as reachability of the acceptable region with the path
constraint switched off. -/
abbrev Recoverable (T : S → A → PMF S) (Pols : Set (S → PMF A))
    (C : Set S) (α : ℝ≥0∞) (n : ℕ) (s₀ : S) : Prop :=
  ConstrainedReachable T Pols C Set.univ α n s₀

/-- A three-way partition of transformation labels into direct, induced, and
exogenous classes. -/
structure AuthorityMap (Act : Type*) where
  direct : Set Act
  induce : Set Act
  exogenous : Set Act
  covers : direct ∪ induce ∪ exogenous = Set.univ
  direct_induce : Disjoint direct induce
  direct_exogenous : Disjoint direct exogenous
  induce_exogenous : Disjoint induce exogenous

/-- Every label belongs to at least one of the three classes. Together with the
disjointness fields, membership is unique. -/
theorem AuthorityMap.classify {Act : Type*} (M : AuthorityMap Act) (a : Act) :
    a ∈ M.direct ∨ a ∈ M.induce ∨ a ∈ M.exogenous := by
  have ha : a ∈ M.direct ∪ M.induce ∪ M.exogenous := M.covers ▸ Set.mem_univ a
  simpa [Set.mem_union, or_assoc] using ha

/-- No label belongs to two of the three classes. -/
theorem AuthorityMap.classify_unique {Act : Type*} (M : AuthorityMap Act) (a : Act) :
    ¬(a ∈ M.direct ∧ a ∈ M.induce) ∧ ¬(a ∈ M.direct ∧ a ∈ M.exogenous) ∧
      ¬(a ∈ M.induce ∧ a ∈ M.exogenous) :=
  ⟨fun ⟨h₁, h₂⟩ => Set.disjoint_left.mp M.direct_induce h₁ h₂,
   fun ⟨h₁, h₂⟩ => Set.disjoint_left.mp M.direct_exogenous h₁ h₂,
   fun ⟨h₁, h₂⟩ => Set.disjoint_left.mp M.induce_exogenous h₁ h₂⟩

/-- A typed three-way classification into `A₀`, `Aother`, and `Ξ`. Using a
nested sum makes the alternatives disjoint by construction. -/
structure PlanPartition (Entry A₀ Aother Ξ : Type*) where
  classify : Entry → A₀ ⊕ (Aother ⊕ Ξ)

namespace PlanPartition

variable {Entry A₀ Aother Ξ : Type*} (P : PlanPartition Entry A₀ Aother Ξ)

/-- Every entry is represented by exactly one constructor of the nested sum. -/
theorem classify_total (e : Entry) :
    (∃ a, P.classify e = Sum.inl a) ∨ (∃ b, P.classify e = Sum.inr (Sum.inl b)) ∨
      (∃ x, P.classify e = Sum.inr (Sum.inr x)) := by
  rcases h : P.classify e with a | b | x
  · exact Or.inl ⟨a, rfl⟩
  · exact Or.inr (Or.inl ⟨b, rfl⟩)
  · exact Or.inr (Or.inr ⟨x, rfl⟩)

/-- An entry classified by the third constructor cannot also be classified by
the first constructor. -/
theorem driver_not_lever {e : Entry} {x : Ξ}
    (h : P.classify e = Sum.inr (Sum.inr x)) : ¬∃ a, P.classify e = Sum.inl a := by
  rintro ⟨a, ha⟩
  rw [h] at ha
  simp at ha

/-- The typed partition induces three subsets that cover the domain and are
pairwise disjoint. -/
def toAuthorityMap : AuthorityMap Entry where
  direct := {e | ∃ a, P.classify e = Sum.inl a}
  induce := {e | ∃ b, P.classify e = Sum.inr (Sum.inl b)}
  exogenous := {e | ∃ x, P.classify e = Sum.inr (Sum.inr x)}
  covers := by
    ext e
    simp only [Set.mem_union, Set.mem_ofPred_eq, Set.mem_univ, iff_true]
    rcases P.classify_total e with h | h | h
    · exact Or.inl (Or.inl h)
    · exact Or.inl (Or.inr h)
    · exact Or.inr h
  direct_induce := by
    rw [Set.disjoint_left]
    rintro e ⟨a, ha⟩ ⟨b, hb⟩
    rw [ha] at hb
    simp at hb
  direct_exogenous := by
    rw [Set.disjoint_left]
    rintro e ⟨a, ha⟩ ⟨x, hx⟩
    rw [ha] at hx
    simp at hx
  induce_exogenous := by
    rw [Set.disjoint_left]
    rintro e ⟨b, hb⟩ ⟨x, hx⟩
    rw [hb] at hx
    simp at hx

end PlanPartition

/-! ## Observation lag

The formal data are a sequence `obs a n : Ω` for each `a` and a discrepancy
function `dist : Ω → Ω → ℝ≥0∞`. One intended instance takes `Ω` to be a space
of observation laws. The comparison action is an explicit argument. -/

variable {Ω : Type*}

/-- The first index at which the declared discrepancy between the two sequences
is at least `δ`, represented in `ℕ∞`. If no such index exists, the infimum is
`⊤`. -/
def obsLag (dist : Ω → Ω → ℝ≥0∞) (obs : A → ℕ → Ω) (δ : ℝ≥0∞) (a a' : A) : ℕ∞ :=
  sInf {τ : ℕ∞ | ∃ n : ℕ, τ = n ∧ δ ≤ dist (obs a n) (obs a' n)}

/-- At any natural index strictly below the lag, the declared discrepancy is
strictly below `δ`. -/
theorem no_signal_before_lag {dist : Ω → Ω → ℝ≥0∞} {obs : A → ℕ → Ω}
    {δ : ℝ≥0∞} {a a' : A} {Δ : ℕ}
    (h : (Δ : ℕ∞) < obsLag dist obs δ a a') :
    dist (obs a Δ) (obs a' Δ) < δ := by
  by_contra hc
  push Not at hc
  have hmem : (Δ : ℕ∞) ∈ {τ : ℕ∞ | ∃ n : ℕ, τ = n ∧ δ ≤ dist (obs a n) (obs a' n)} :=
    ⟨Δ, rfl, hc⟩
  exact absurd (sInf_le hmem) (not_le.mpr h)

/-- Demanding a stronger signal never shortens the wait: the observability
lag is monotone in the resolution `δ`. (Also proved independently by
Harmonic's Aristotle prover; see `aristotle/`.) -/
theorem obsLag_mono_resolution (dist : Ω → Ω → ℝ≥0∞) (obs : A → ℕ → Ω)
    {δ δ' : ℝ≥0∞} (h : δ ≤ δ') (a a' : A) :
    obsLag dist obs δ a a' ≤ obsLag dist obs δ' a a' := by
  refine sInf_le_sInf ?_
  rintro τ ⟨n, rfl, hn⟩
  exact ⟨n, rfl, h.trans hn⟩

/-- The lag is finite exactly when the discrepancy reaches `δ` at some natural
index. -/
theorem obsLag_ne_top_iff {dist : Ω → Ω → ℝ≥0∞} {obs : A → ℕ → Ω}
    {δ : ℝ≥0∞} {a a' : A} :
    obsLag dist obs δ a a' ≠ ⊤ ↔ ∃ n : ℕ, δ ≤ dist (obs a n) (obs a' n) := by
  rw [obsLag, ne_eq, sInf_eq_top]
  push Not
  constructor
  · rintro ⟨τ, ⟨n, rfl, hn⟩, -⟩
    exact ⟨n, hn⟩
  · rintro ⟨n, hn⟩
    exact ⟨n, ⟨n, rfl, hn⟩, by simp⟩

/-- The triangle law for lags: with a triangle inequality on `dist`, the
lag against `a''` at resolution `δ` is bounded below by the smaller of the
two half-resolution lags through an arbitrary comparison action `a'`.
(Proof found by Harmonic's Aristotle; see
`aristotle/pool/lagtriangle/`.) -/
theorem min_obsLag_le (dist : Ω → Ω → ℝ≥0∞) (obs : A → ℕ → Ω)
    (htri : ∀ x y z, dist x z ≤ dist x y + dist y z)
    (δ : ℝ≥0∞) (a a' a'' : A) :
    min (obsLag dist obs (δ / 2) a a') (obsLag dist obs (δ / 2) a' a'')
      ≤ obsLag dist obs δ a a'' := by
  unfold obsLag
  apply le_sInf
  intro τ hτ
  rcases hτ with ⟨n, rfl, hn⟩
  by_cases h₁ : δ / 2 ≤ dist (obs a n) (obs a' n)
  · exact le_trans (min_le_left _ _) (sInf_le ⟨n, rfl, h₁⟩)
  · have h₂ : δ / 2 ≤ dist (obs a' n) (obs a'' n) := by
      by_contra h₂
      have hadd := ENNReal.add_lt_add (lt_of_not_ge h₁) (lt_of_not_ge h₂)
      rw [ENNReal.add_halves] at hadd
      exact (not_lt_of_ge (hn.trans (htri _ _ _))) hadd
    exact le_trans (min_le_right _ _) (sInf_le ⟨n, rfl, h₂⟩)

/-! ## Product-state augmentation -/

/-- One step of a reflexive system: the transition depends on the other
agents' current policy configuration `p : P`, and that configuration adapts
in response to the focal action via `U`. -/
def extendStep (T : S → A → P → PMF S) (U : P → A → P) :
    S × P → A → PMF (S × P) :=
  fun sp a => (T sp.1 a sp.2).map fun s' => (s', U sp.2 a)

/-- The first marginal of one augmented step, conditional on the current
product state and action, is the supplied `P`-dependent transition on `S`.
This does not make the projected `S` process autonomous or Markovian. -/
theorem extendStep_fst (T : S → A → P → PMF S) (U : P → A → P)
    (sp : S × P) (a : A) :
    (extendStep T U sp a).map Prod.fst = T sp.1 a sp.2 := by
  simp only [extendStep]
  rw [PMF.map_comp]
  have h : (Prod.fst ∘ fun s' : S => (s', U sp.2 a)) = id := rfl
  rw [h, PMF.map_id]

/-- Stochastic adaptation with a factorized update: conditional on the current
product state and action, the next `S` state and next policy configuration are
sampled independently. Dependence on the realized next state or payoff would
require a joint or conditional kernel. -/
def extendStepRand (T : S → A → P → PMF S) (U : P → A → PMF P) :
    S × P → A → PMF (S × P) :=
  fun sp a => (T sp.1 a sp.2).bind fun s' => (U sp.2 a).map fun p' => (s', p')

/-- The first marginal of the factorized stochastic augmentation is the supplied
`P`-dependent transition on `S`. -/
theorem extendStepRand_fst (T : S → A → P → PMF S) (U : P → A → PMF P)
    (sp : S × P) (a : A) :
    (extendStepRand T U sp a).map Prod.fst = T sp.1 a sp.2 := by
  have h : ∀ s' : S, ((U sp.2 a).map fun _ => s') = PMF.pure s' := by
    intro s'
    exact PMF.map_const _ _
  simp only [extendStepRand, PMF.map_bind, PMF.map_comp, Function.comp_def]
  simp only [h]
  exact PMF.bind_pure _

end
end HardProblems
