import LeanTest.HardProblems.Core

/-!
# Hard Problems, Chapters 4, 5, 8, 9: agency, latency, reflexivity, probes

One file because the four chapters share the same machinery: trajectory
distributions of a controlled Markov step.

Results proved:

* `constrainedReachable_mono_alpha`, `constrainedReachable_mono_goal`:
  chance-constrained reachability behaves monotonically in the risk budget
  and the target set (sanity conditions the book's definition should satisfy,
  and does).
* `AuthorityMap.classify`: the direct/induce/exogenous partition classifies
  every apparent intervention exactly once.
* `no_signal_before_lag`: reviewing strictly before the observability lag
  cannot produce a discriminating signal at resolution `δ`. This is the
  provable core of chapter 5's overcorrection warning.
* `extendStep_fst`: state augmentation. A reflexive system (chapter 8), where
  other agents' policies update in response to actions, is a Markov system on
  the extended state `S × Π₋₀`. The S-marginal of one extended step recovers
  the original kernel.
* `goodhart_witness_example`: a two-line concrete instance of metric-goal
  decoupling under intervention.
* `not_decisionRelevant_iff`: a probe is decision-irrelevant exactly when its
  action recommendation is constant across possible outcomes (chapter 9's
  practical criterion, stated as an iff).
-/

namespace HardProblems

noncomputable section

open scoped ENNReal
open MeasureTheory

variable {S A O P : Type*}

/-! ## Trajectories (chapter 4) -/

/-- Fold a Markov policy and a transition kernel into a closed-loop step. -/
def stepOf (T : S → A → PMF S) (π : S → PMF A) : S → PMF S :=
  fun s => (π s).bind (T s)

/-- Distribution over length-`(n+1)` trajectories (as lists, initial state
first) generated by a step kernel. -/
def rollout (step : S → PMF S) : ℕ → S → PMF (List S)
  | 0, s => PMF.pure [s]
  | n + 1, s => (step s).bind fun s' => (rollout step n s').map (s :: ·)

/-- The chance-constraint event of chapter 4: the trajectory ends in the
target set `Gset` and never leaves the safe set `C`. -/
def SafeGoal (Gset C : Set S) : Set (List S) :=
  {l | (∃ g ∈ Gset, l.getLast? = some g) ∧ ∀ z ∈ l, z ∈ C}

/-- Success probability of a policy for the safe-reachability event. -/
def successProb (T : S → A → PMF S) (π : S → PMF A)
    (Gset C : Set S) (n : ℕ) (s₀ : S) : ℝ≥0∞ :=
  (rollout (stepOf T π) n s₀).toOuterMeasure (SafeGoal Gset C)

/-- Chapter 4's constrained reachability: some admissible policy reaches the
target within horizon `n`, staying safe, with probability at least `1 - α`. -/
def ConstrainedReachable (T : S → A → PMF S) (Pols : Set (S → PMF A))
    (Gset C : Set S) (α : ℝ≥0∞) (n : ℕ) (s₀ : S) : Prop :=
  ∃ π ∈ Pols, 1 - α ≤ successProb T π Gset C n s₀

/-- A larger risk budget can only help. -/
theorem constrainedReachable_mono_alpha
    {T : S → A → PMF S} {Pols : Set (S → PMF A)} {Gset C : Set S}
    {α α' : ℝ≥0∞} {n : ℕ} {s₀ : S} (hα : α ≤ α')
    (h : ConstrainedReachable T Pols Gset C α n s₀) :
    ConstrainedReachable T Pols Gset C α' n s₀ := by
  obtain ⟨π, hπ, hp⟩ := h
  exact ⟨π, hπ, le_trans (tsub_le_tsub_left hα 1) hp⟩

/-- Enlarging the target set can only help. -/
theorem constrainedReachable_mono_goal
    {T : S → A → PMF S} {Pols : Set (S → PMF A)} {Gset Gset' C : Set S}
    {α : ℝ≥0∞} {n : ℕ} {s₀ : S} (hG : Gset ⊆ Gset')
    (h : ConstrainedReachable T Pols Gset C α n s₀) :
    ConstrainedReachable T Pols Gset' C α n s₀ := by
  obtain ⟨π, hπ, hp⟩ := h
  refine ⟨π, hπ, le_trans hp (measure_mono ?_)⟩
  rintro l ⟨⟨g, hg, hlast⟩, hsafe⟩
  exact ⟨⟨g, hG hg, hlast⟩, hsafe⟩

/-- The reversibility coordinate `R` of the hardness profile, as a special
case: recovery is reachability of the acceptable region with the path
constraint switched off. -/
abbrev Recoverable (T : S → A → PMF S) (Pols : Set (S → PMF A))
    (C : Set S) (α : ℝ≥0∞) (n : ℕ) (s₀ : S) : Prop :=
  ConstrainedReachable T Pols C Set.univ α n s₀

/-- Chapter 4's authority map: a partition of apparent interventions into
directly controlled, inducible, and exogenous. -/
structure AuthorityMap (Act : Type*) where
  direct : Set Act
  induce : Set Act
  exogenous : Set Act
  covers : direct ∪ induce ∪ exogenous = Set.univ
  direct_induce : Disjoint direct induce
  direct_exogenous : Disjoint direct exogenous
  induce_exogenous : Disjoint induce exogenous

/-- Every apparent intervention is classified. Combined with the disjointness
fields, the classification is unique: "take ownership" is not a category. -/
theorem AuthorityMap.classify {Act : Type*} (M : AuthorityMap Act) (a : Act) :
    a ∈ M.direct ∨ a ∈ M.induce ∨ a ∈ M.exogenous := by
  have ha : a ∈ M.direct ∪ M.induce ∪ M.exogenous := M.covers ▸ Set.mem_univ a
  simpa [Set.mem_union, or_assoc] using ha

/-- The classification is exclusive as well as total: no intervention lands
in two cells of the authority map (immediate from the map's disjointness
requirements, recorded so that "exactly one" is a stated proposition). -/
theorem AuthorityMap.classify_unique {Act : Type*} (M : AuthorityMap Act) (a : Act) :
    ¬(a ∈ M.direct ∧ a ∈ M.induce) ∧ ¬(a ∈ M.direct ∧ a ∈ M.exogenous) ∧
      ¬(a ∈ M.induce ∧ a ∈ M.exogenous) :=
  ⟨fun ⟨h₁, h₂⟩ => Set.disjoint_left.mp M.direct_induce h₁ h₂,
   fun ⟨h₁, h₂⟩ => Set.disjoint_left.mp M.direct_exogenous h₁ h₂,
   fun ⟨h₁, h₂⟩ => Set.disjoint_left.mp M.induce_exogenous h₁ h₂⟩

/-- The authority map, typed so the category mistake is unrepresentable: a
plan entry classifies as a focal lever (realizing as a focal action `A₀`),
an inducible (realizing as a counterparty action `Aother`), or an exogenous
driver (realizing as an environment input `Ξ`, which is not an action at
all). Because classification is a function into a sum, totality and
exclusivity are theorems rather than axioms, and a driver misfiled as a
lever is a type error rather than a discipline. -/
structure PlanPartition (Entry A₀ Aother Ξ : Type*) where
  classify : Entry → A₀ ⊕ (Aother ⊕ Ξ)

namespace PlanPartition

variable {Entry A₀ Aother Ξ : Type*} (P : PlanPartition Entry A₀ Aother Ξ)

/-- Every plan entry is classified: totality is structural. -/
theorem classify_total (e : Entry) :
    (∃ a, P.classify e = Sum.inl a) ∨ (∃ b, P.classify e = Sum.inr (Sum.inl b)) ∨
      (∃ x, P.classify e = Sum.inr (Sum.inr x)) := by
  rcases h : P.classify e with a | b | x
  · exact Or.inl ⟨a, rfl⟩
  · exact Or.inr (Or.inl ⟨b, rfl⟩)
  · exact Or.inr (Or.inr ⟨x, rfl⟩)

/-- A driver has no realization as a lever: the category mistake the
untyped map merely legislated against is here impossible to state. -/
theorem driver_not_lever {e : Entry} {x : Ξ}
    (h : P.classify e = Sum.inr (Sum.inr x)) : ¬∃ a, P.classify e = Sum.inl a := by
  rintro ⟨a, ha⟩
  rw [h] at ha
  simp at ha

/-- The typed partition induces the set-based authority map, and the old
structure's axioms (coverage, pairwise disjointness) fall out as theorems:
what had to be assumed of three sets is guaranteed by one function. -/
def toAuthorityMap : AuthorityMap Entry where
  direct := {e | ∃ a, P.classify e = Sum.inl a}
  induce := {e | ∃ b, P.classify e = Sum.inr (Sum.inl b)}
  exogenous := {e | ∃ x, P.classify e = Sum.inr (Sum.inr x)}
  covers := by
    ext e
    simp only [Set.mem_union, Set.mem_ofPred_eq, Set.mem_univ, iff_true]
    rcases P.classify_total e with h | h | h
    · exact Or.inl (Or.inl h)
    · exact Or.inl (Or.inr h)
    · exact Or.inr h
  direct_induce := by
    rw [Set.disjoint_left]
    rintro e ⟨a, ha⟩ ⟨b, hb⟩
    rw [ha] at hb
    simp at hb
  direct_exogenous := by
    rw [Set.disjoint_left]
    rintro e ⟨a, ha⟩ ⟨x, hx⟩
    rw [ha] at hx
    simp at hx
  induce_exogenous := by
    rw [Set.disjoint_left]
    rintro e ⟨b, hb⟩ ⟨x, hx⟩
    rw [hb] at hx
    simp at hx

end PlanPartition

/-! ## Latency (chapter 5)

`obs a n` is the marginal law of the observable at `n` steps after doing `a`;
`dist` is any distributional distance. The book's `τ_δ(a)` leaves the
comparison action implicit; here it is an explicit argument. -/

variable {Ω : Type*}

/-- Observability lag at resolution `δ` between actions `a` and `a'`: the
first time their observable consequences differ by at least `δ`. Equals `⊤`
when the two actions are never `δ`-distinguishable, which is the honest
convention for "this intervention is unobservable at this resolution". -/
def obsLag (dist : Ω → Ω → ℝ≥0∞) (obs : A → ℕ → Ω) (δ : ℝ≥0∞) (a a' : A) : ℕ∞ :=
  sInf {τ : ℕ∞ | ∃ n : ℕ, τ = n ∧ δ ≤ dist (obs a n) (obs a' n)}

/-- Reviewing strictly before the lag yields no discriminating signal: at any
cadence `Δ < τ_δ`, the observable laws under `a` and `a'` are still within
`δ` of each other. Whatever a fast review concludes, it is not evidence that
distinguishes the intervention from its alternative. -/
theorem no_signal_before_lag {dist : Ω → Ω → ℝ≥0∞} {obs : A → ℕ → Ω}
    {δ : ℝ≥0∞} {a a' : A} {Δ : ℕ}
    (h : (Δ : ℕ∞) < obsLag dist obs δ a a') :
    dist (obs a Δ) (obs a' Δ) < δ := by
  by_contra hc
  push Not at hc
  have hmem : (Δ : ℕ∞) ∈ {τ : ℕ∞ | ∃ n : ℕ, τ = n ∧ δ ≤ dist (obs a n) (obs a' n)} :=
    ⟨Δ, rfl, hc⟩
  exact absurd (sInf_le hmem) (not_le.mpr h)

end
end HardProblems
