import LeanTest.HardProblems.Core

/-!
# Hard Problems, Chapters 4, 5, 8, 9: agency, latency, reflexivity, probes

One file because the four chapters share the same machinery: trajectory
distributions of a controlled Markov step.

Results proved:

* `constrainedReachable_mono_alpha`, `constrainedReachable_mono_goal`:
  chance-constrained reachability behaves monotonically in the risk budget
  and the target set (sanity conditions the book's definition should satisfy,
  and does).
* `AuthorityMap.classify`: the direct/induce/exogenous partition classifies
  every apparent intervention exactly once.
* `no_signal_before_lag`: reviewing strictly before the observability lag
  cannot produce a discriminating signal at resolution `δ`. This is the
  provable core of chapter 5's overcorrection warning.
* `extendStep_fst`: state augmentation. A reflexive system (chapter 8), where
  other agents' policies update in response to actions, is a Markov system on
  the extended state `S × Π₋₀`. The S-marginal of one extended step recovers
  the original kernel.
* `goodhart_witness_example`: a two-line concrete instance of metric-goal
  decoupling under intervention.
* `not_decisionRelevant_iff`: a probe is decision-irrelevant exactly when its
  action recommendation is constant across possible outcomes (chapter 9's
  practical criterion, stated as an iff).
-/

namespace HardProblems

noncomputable section

open scoped ENNReal
open MeasureTheory

variable {S A O P : Type*}

/-! ## Trajectories (chapter 4) -/

/-- Fold a Markov policy and a transition kernel into a closed-loop step. -/
def stepOf (T : S → A → PMF S) (π : S → PMF A) : S → PMF S :=
  fun s => (π s).bind (T s)

/-- Distribution over length-`(n+1)` trajectories (as lists, initial state
first) generated by a step kernel. -/
def rollout (step : S → PMF S) : ℕ → S → PMF (List S)
  | 0, s => PMF.pure [s]
  | n + 1, s => (step s).bind fun s' => (rollout step n s').map (s :: ·)

/-- The chance-constraint event of chapter 4: the trajectory ends in the
target set `Gset` and never leaves the safe set `C`. -/
def SafeGoal (Gset C : Set S) : Set (List S) :=
  {l | (∃ g ∈ Gset, l.getLast? = some g) ∧ ∀ z ∈ l, z ∈ C}

/-- Success probability of a policy for the safe-reachability event. -/
def successProb (T : S → A → PMF S) (π : S → PMF A)
    (Gset C : Set S) (n : ℕ) (s₀ : S) : ℝ≥0∞ :=
  (rollout (stepOf T π) n s₀).toOuterMeasure (SafeGoal Gset C)

/-- Chapter 4's constrained reachability: some admissible policy reaches the
target within horizon `n`, staying safe, with probability at least `1 - α`. -/
def ConstrainedReachable (T : S → A → PMF S) (Pols : Set (S → PMF A))
    (Gset C : Set S) (α : ℝ≥0∞) (n : ℕ) (s₀ : S) : Prop :=
  ∃ π ∈ Pols, 1 - α ≤ successProb T π Gset C n s₀

/-- A larger risk budget can only help. -/
theorem constrainedReachable_mono_alpha
    {T : S → A → PMF S} {Pols : Set (S → PMF A)} {Gset C : Set S}
    {α α' : ℝ≥0∞} {n : ℕ} {s₀ : S} (hα : α ≤ α')
    (h : ConstrainedReachable T Pols Gset C α n s₀) :
    ConstrainedReachable T Pols Gset C α' n s₀ := by
  obtain ⟨π, hπ, hp⟩ := h
  exact ⟨π, hπ, le_trans (tsub_le_tsub_left hα 1) hp⟩

/-- Enlarging the target set can only help. -/
theorem constrainedReachable_mono_goal
    {T : S → A → PMF S} {Pols : Set (S → PMF A)} {Gset Gset' C : Set S}
    {α : ℝ≥0∞} {n : ℕ} {s₀ : S} (hG : Gset ⊆ Gset')
    (h : ConstrainedReachable T Pols Gset C α n s₀) :
    ConstrainedReachable T Pols Gset' C α n s₀ := by
  obtain ⟨π, hπ, hp⟩ := h
  refine ⟨π, hπ, le_trans hp (measure_mono ?_)⟩
  rintro l ⟨⟨g, hg, hlast⟩, hsafe⟩
  exact ⟨⟨g, hG hg, hlast⟩, hsafe⟩

/-- The reversibility coordinate `R` of the hardness profile, as a special
case: recovery is reachability of the acceptable region with the path
constraint switched off. -/
abbrev Recoverable (T : S → A → PMF S) (Pols : Set (S → PMF A))
    (C : Set S) (α : ℝ≥0∞) (n : ℕ) (s₀ : S) : Prop :=
  ConstrainedReachable T Pols C Set.univ α n s₀

/-- Chapter 4's authority map: a partition of apparent interventions into
directly controlled, inducible, and exogenous. -/
structure AuthorityMap (Act : Type*) where
  direct : Set Act
  induce : Set Act
  exogenous : Set Act
  covers : direct ∪ induce ∪ exogenous = Set.univ
  direct_induce : Disjoint direct induce
  direct_exogenous : Disjoint direct exogenous
  induce_exogenous : Disjoint induce exogenous

/-- Every apparent intervention is classified. Combined with the disjointness
fields, the classification is unique: "take ownership" is not a category. -/
theorem AuthorityMap.classify {Act : Type*} (M : AuthorityMap Act) (a : Act) :
    a ∈ M.direct ∨ a ∈ M.induce ∨ a ∈ M.exogenous := by
  have ha : a ∈ M.direct ∪ M.induce ∪ M.exogenous := M.covers ▸ Set.mem_univ a
  simpa [Set.mem_union, or_assoc] using ha

/-- The classification is exclusive as well as total: no intervention lands
in two cells of the authority map (immediate from the map's disjointness
requirements, recorded so that "exactly one" is a stated proposition). -/
theorem AuthorityMap.classify_unique {Act : Type*} (M : AuthorityMap Act) (a : Act) :
    ¬(a ∈ M.direct ∧ a ∈ M.induce) ∧ ¬(a ∈ M.direct ∧ a ∈ M.exogenous) ∧
      ¬(a ∈ M.induce ∧ a ∈ M.exogenous) :=
  ⟨fun ⟨h₁, h₂⟩ => Set.disjoint_left.mp M.direct_induce h₁ h₂,
   fun ⟨h₁, h₂⟩ => Set.disjoint_left.mp M.direct_exogenous h₁ h₂,
   fun ⟨h₁, h₂⟩ => Set.disjoint_left.mp M.induce_exogenous h₁ h₂⟩

/-- The authority map, typed so the category mistake is unrepresentable: a
plan entry classifies as a focal lever (realizing as a focal action `A₀`),
an inducible (realizing as a counterparty action `Aother`), or an exogenous
driver (realizing as an environment input `Ξ`, which is not an action at
all). Because classification is a function into a sum, totality and
exclusivity are theorems rather than axioms, and a driver misfiled as a
lever is a type error rather than a discipline. -/
structure PlanPartition (Entry A₀ Aother Ξ : Type*) where
  classify : Entry → A₀ ⊕ (Aother ⊕ Ξ)

namespace PlanPartition

variable {Entry A₀ Aother Ξ : Type*} (P : PlanPartition Entry A₀ Aother Ξ)

/-- Every plan entry is classified: totality is structural. -/
theorem classify_total (e : Entry) :
    (∃ a, P.classify e = Sum.inl a) ∨ (∃ b, P.classify e = Sum.inr (Sum.inl b)) ∨
      (∃ x, P.classify e = Sum.inr (Sum.inr x)) := by
  rcases h : P.classify e with a | b | x
  · exact Or.inl ⟨a, rfl⟩
  · exact Or.inr (Or.inl ⟨b, rfl⟩)
  · exact Or.inr (Or.inr ⟨x, rfl⟩)

/-- A driver has no realization as a lever: the category mistake the
untyped map merely legislated against is here impossible to state. -/
theorem driver_not_lever {e : Entry} {x : Ξ}
    (h : P.classify e = Sum.inr (Sum.inr x)) : ¬∃ a, P.classify e = Sum.inl a := by
  rintro ⟨a, ha⟩
  rw [h] at ha
  simp at ha

/-- The typed partition induces the set-based authority map, and the old
structure's axioms (coverage, pairwise disjointness) fall out as theorems:
what had to be assumed of three sets is guaranteed by one function. -/
def toAuthorityMap : AuthorityMap Entry where
  direct := {e | ∃ a, P.classify e = Sum.inl a}
  induce := {e | ∃ b, P.classify e = Sum.inr (Sum.inl b)}
  exogenous := {e | ∃ x, P.classify e = Sum.inr (Sum.inr x)}
  covers := by
    ext e
    simp only [Set.mem_union, Set.mem_ofPred_eq, Set.mem_univ, iff_true]
    rcases P.classify_total e with h | h | h
    · exact Or.inl (Or.inl h)
    · exact Or.inl (Or.inr h)
    · exact Or.inr h
  direct_induce := by
    rw [Set.disjoint_left]
    rintro e ⟨a, ha⟩ ⟨b, hb⟩
    rw [ha] at hb
    simp at hb
  direct_exogenous := by
    rw [Set.disjoint_left]
    rintro e ⟨a, ha⟩ ⟨x, hx⟩
    rw [ha] at hx
    simp at hx
  induce_exogenous := by
    rw [Set.disjoint_left]
    rintro e ⟨b, hb⟩ ⟨x, hx⟩
    rw [hb] at hx
    simp at hx

end PlanPartition

/-! ## Latency (chapter 5)

`obs a n` is the marginal law of the observable at `n` steps after doing `a`;
`dist` is any distributional distance. The book's `τ_δ(a)` leaves the
comparison action implicit; here it is an explicit argument. -/

variable {Ω : Type*}

/-- Observability lag at resolution `δ` between actions `a` and `a'`: the
first time their observable consequences differ by at least `δ`. Equals `⊤`
when the two actions are never `δ`-distinguishable, which is the honest
convention for "this intervention is unobservable at this resolution". -/
def obsLag (dist : Ω → Ω → ℝ≥0∞) (obs : A → ℕ → Ω) (δ : ℝ≥0∞) (a a' : A) : ℕ∞ :=
  sInf {τ : ℕ∞ | ∃ n : ℕ, τ = n ∧ δ ≤ dist (obs a n) (obs a' n)}

/-- Reviewing strictly before the lag yields no discriminating signal: at any
cadence `Δ < τ_δ`, the observable laws under `a` and `a'` are still within
`δ` of each other. Whatever a fast review concludes, it is not evidence that
distinguishes the intervention from its alternative. -/
theorem no_signal_before_lag {dist : Ω → Ω → ℝ≥0∞} {obs : A → ℕ → Ω}
    {δ : ℝ≥0∞} {a a' : A} {Δ : ℕ}
    (h : (Δ : ℕ∞) < obsLag dist obs δ a a') :
    dist (obs a Δ) (obs a' Δ) < δ := by
  by_contra hc
  push Not at hc
  have hmem : (Δ : ℕ∞) ∈ {τ : ℕ∞ | ∃ n : ℕ, τ = n ∧ δ ≤ dist (obs a n) (obs a' n)} :=
    ⟨Δ, rfl, hc⟩
  exact absurd (sInf_le hmem) (not_le.mpr h)

/-- Demanding a stronger signal never shortens the wait: the observability
lag is monotone in the resolution `δ`. (Also proved independently by
Harmonic's Aristotle prover; see `aristotle/`.) -/
theorem obsLag_mono_resolution (dist : Ω → Ω → ℝ≥0∞) (obs : A → ℕ → Ω)
    {δ δ' : ℝ≥0∞} (h : δ ≤ δ') (a a' : A) :
    obsLag dist obs δ a a' ≤ obsLag dist obs δ' a a' := by
  refine sInf_le_sInf ?_
  rintro τ ⟨n, rfl, hn⟩
  exact ⟨n, rfl, h.trans hn⟩

/-- Latency is observability with a clock: the lag against a comparison is
finite exactly when some horizon distinguishes the two actions at
resolution `δ`. An infinite lag is an observability failure for the pair,
which is why the profile's L and O coordinates are one diagnostic. -/
theorem obsLag_ne_top_iff {dist : Ω → Ω → ℝ≥0∞} {obs : A → ℕ → Ω}
    {δ : ℝ≥0∞} {a a' : A} :
    obsLag dist obs δ a a' ≠ ⊤ ↔ ∃ n : ℕ, δ ≤ dist (obs a n) (obs a' n) := by
  rw [obsLag, ne_eq, sInf_eq_top]
  push Not
  constructor
  · rintro ⟨τ, ⟨n, rfl, hn⟩, -⟩
    exact ⟨n, hn⟩
  · rintro ⟨n, hn⟩
    exact ⟨n, ⟨n, rfl, hn⟩, by simp⟩

/-- The triangle law for lags: with a triangle inequality on `dist`, the
lag against `a''` at resolution `δ` is bounded below by the smaller of the
two half-resolution lags through any intermediate comparison `a'`. Waiting
for a strong signal against a far alternative is bounded by half-signals
through any action between them. (Proof found by Harmonic's Aristotle; see
`aristotle/pool/lagtriangle/`.) -/
theorem min_obsLag_le (dist : Ω → Ω → ℝ≥0∞) (obs : A → ℕ → Ω)
    (htri : ∀ x y z, dist x z ≤ dist x y + dist y z)
    (δ : ℝ≥0∞) (a a' a'' : A) :
    min (obsLag dist obs (δ / 2) a a') (obsLag dist obs (δ / 2) a' a'')
      ≤ obsLag dist obs δ a a'' := by
  unfold obsLag
  apply le_sInf
  intro τ hτ
  rcases hτ with ⟨n, rfl, hn⟩
  by_cases h₁ : δ / 2 ≤ dist (obs a n) (obs a' n)
  · exact le_trans (min_le_left _ _) (sInf_le ⟨n, rfl, h₁⟩)
  · have h₂ : δ / 2 ≤ dist (obs a' n) (obs a'' n) := by
      by_contra h₂
      have hadd := ENNReal.add_lt_add (lt_of_not_ge h₁) (lt_of_not_ge h₂)
      rw [ENNReal.add_halves] at hadd
      exact (not_lt_of_ge (hn.trans (htri _ _ _))) hadd
    exact le_trans (min_le_right _ _) (sInf_le ⟨n, rfl, h₂⟩)

/-! ## Reflexivity (chapter 8) -/

/-- One step of a reflexive system: the transition depends on the other
agents' current policy configuration `p : P`, and that configuration adapts
in response to the focal action via `U`. -/
def extendStep (T : S → A → P → PMF S) (U : P → A → P) :
    S × P → A → PMF (S × P) :=
  fun sp a => (T sp.1 a sp.2).map fun s' => (s', U sp.2 a)

/-- State augmentation: the extended system is an ordinary Markov kernel on
`S × P`, and its state marginal recovers the original transition. Reflexivity
is therefore not beyond the formalism; it relocates the state. The cost is
that `P` is typically unobserved, which feeds back into chapter 3. -/
theorem extendStep_fst (T : S → A → P → PMF S) (U : P → A → P)
    (sp : S × P) (a : A) :
    (extendStep T U sp a).map Prod.fst = T sp.1 a sp.2 := by
  simp only [extendStep]
  rw [PMF.map_comp]
  have h : (Prod.fst ∘ fun s' : S => (s', U sp.2 a)) = id := rfl
  rw [h, PMF.map_id]

/-- Stochastic adaptation: the operator returns a distribution over next
policy configurations. Dependence on observations or realized payoffs folds
into the policy coordinate `P` the same way. -/
def extendStepRand (T : S → A → P → PMF S) (U : P → A → PMF P) :
    S × P → A → PMF (S × P) :=
  fun sp a => (T sp.1 a sp.2).bind fun s' => (U sp.2 a).map fun p' => (s', p')

/-- The state marginal of the stochastic augmentation also recovers the
original kernel: randomizing the adaptation does not change the conclusion
of `extendStep_fst`. -/
theorem extendStepRand_fst (T : S → A → P → PMF S) (U : P → A → PMF P)
    (sp : S × P) (a : A) :
    (extendStepRand T U sp a).map Prod.fst = T sp.1 a sp.2 := by
  have h : ∀ s' : S, ((U sp.2 a).map fun _ => s') = PMF.pure s' := by
    intro s'
    exact PMF.map_const _ _
  simp only [extendStepRand, PMF.map_bind, PMF.map_comp, Function.comp_def]
  simp only [h]
  exact PMF.bind_pure _

end
end HardProblems
